import{useEffect,useMemo,useRef,useState}from'react';import{AnimatePresence,motion,useMotionValue,useSpring,useTransform}from'framer-motion';import{ArrowDown,ArrowRight,ExternalLink,Menu,Search,Scale,Star,X,Sparkles,MousePointer2,ShieldCheck,Zap,Heart,ChevronDown}from'lucide-react';import{products as fallback,posts,Product}from'./data';

const SHEET_URL=import.meta.env.VITE_SHEET_CSV_URL as string|undefined;
async function loadProducts():Promise<Product[]>{if(!SHEET_URL)return fallback;try{const r=await fetch(SHEET_URL);const csv=await r.text();const rows=csv.trim().split(/\r?\n/).map(x=>x.split(',').map(v=>v.replace(/^"|"$/g,'')));const h=rows.shift()||[];return rows.map((row,i)=>{const o=Object.fromEntries(h.map((k,j)=>[k,row[j]||'']));return{id:o.id||'sheet-'+i,name:o.name,category:o.category||'Otros',price:o.price||'',rating:Number(o.rating)||4.5,tag:o.tag||'Recomendado',image:o.image,description:o.description,pros:(o.pros||'').split('|').filter(Boolean),affiliateUrl:o.affiliateUrl||'#'}})}catch{return fallback}}

function ScrollProgress(){const[p,setP]=useState(0);useEffect(()=>{const f=()=>{const h=document.documentElement;setP(window.scrollY/(h.scrollHeight-h.clientHeight)*100)};window.addEventListener('scroll',f,{passive:true});f();return()=>window.removeEventListener('scroll',f)},[]);return <div className="scroll-progress" style={{transform:'scaleX('+p/100+')'}}/>}

function Reveal({children,className='',delay=0}:{children:React.ReactNode;className?:string;delay?:number}){return <motion.div className={className} initial={{opacity:0,y:34,filter:'blur(10px)'}} whileInView={{opacity:1,y:0,filter:'blur(0px)'}} viewport={{once:true,margin:'-80px'}} transition={{duration:.75,delay,ease:[.22,1,.36,1]}}>{children}</motion.div>}

function Magnetic({children,className='' }:{children:React.ReactNode;className?:string}){const x=useMotionValue(0),y=useMotionValue(0),sx=useSpring(x,{stiffness:180,damping:14}),sy=useSpring(y,{stiffness:180,damping:14});return <motion.div className={className} style={{x:sx,y:sy}} onMouseMove={e=>{const r=e.currentTarget.getBoundingClientRect();x.set((e.clientX-r.left-r.width/2)*.18);y.set((e.clientY-r.top-r.height/2)*.18)}} onMouseLeave={()=>{x.set(0);y.set(0)}}>{children}</motion.div>}

function TiltCard({children,className='' }:{children:React.ReactNode;className?:string}){const ref=useRef<HTMLDivElement>(null);const rx=useMotionValue(0),ry=useMotionValue(0),sx=useSpring(rx,{stiffness:180,damping:20}),sy=useSpring(ry,{stiffness:180,damping:20});return <motion.div ref={ref} className={className} style={{rotateX:sx,rotateY:sy,transformPerspective:900}} onMouseMove={e=>{const r=e.currentTarget.getBoundingClientRect();rx.set(-((e.clientY-r.top)/r.height-.5)*7);ry.set(((e.clientX-r.left)/r.width-.5)*7)}} onMouseLeave={()=>{rx.set(0);ry.set(0)}}>{children}</motion.div>}

function WordReveal(){return <div className="hero-title"><div className="line"><motion.span initial={{y:'110%'}} animate={{y:0}} transition={{duration:.9,ease:[.22,1,.36,1]}}>Todo lo que</motion.span></div><div className="line"><motion.span initial={{y:'110%'}} animate={{y:0}} transition={{duration:.9,delay:.08,ease:[.22,1,.36,1]}}>tu mascota</motion.span></div><div className="line serif"><motion.span initial={{y:'110%'}} animate={{y:0}} transition={{duration:1,delay:.16,ease:[.22,1,.36,1]}}>necesita.</motion.span></div></div>}

export default function App(){const[items,setItems]=useState<Product[]>(fallback),[category,setCategory]=useState('Todos'),[compare,setCompare]=useState<Product[]>([]),[search,setSearch]=useState(''),[menu,setMenu]=useState(false),[mouse,setMouse]=useState({x:0,y:0});useEffect(()=>{loadProducts().then(setItems);const f=(e:MouseEvent)=>setMouse({x:e.clientX,y:e.clientY});window.addEventListener('mousemove',f,{passive:true});return()=>window.removeEventListener('mousemove',f)},[]);const cats=['Todos',...Array.from(new Set(items.map(p=>p.category)))];const visible=useMemo(()=>items.filter(p=>(category==='Todos'||p.category===category)&&p.name.toLowerCase().includes(search.toLowerCase())),[items,category,search]);const toggle=(p:Product)=>setCompare(c=>c.some(x=>x.id===p.id)?c.filter(x=>x.id!==p.id):c.length<3?[...c,p]:c);

return <div className="app"><ScrollProgress/><div className="cursor-glow" style={{left:mouse.x,top:mouse.y}}/><div className="noise"/><header className="nav"><a className="logo" href="#"><span className="logo-mark">M</span>miwuko</a><nav className={menu?'open':''}><a href="#productos">Productos</a><a href="#metodo">Método</a><a href="#comparador">Comparador</a><a href="#guias">Guías</a></nav><Magnetic className="nav-cta"><a href="#productos">Explorar <ArrowRight size={14}/></a></Magnetic><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>

<main><section className="hero"><div className="hero-grid"/><div className="hero-copy"><motion.div className="eyebrow" initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.25}}><span className="eyebrow-dot"/> RECOMENDACIONES PARA GENTE QUE QUIERE ELEGIR BIEN</motion.div><WordReveal/><motion.p initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.5}}>Productos, comparativas y guías prácticas para cuidar mejor de ellos <em>sin perder horas buscando.</em></motion.p><div className="hero-actions"><Magnetic><a className="btn primary" href="#productos">Descubrir selección <ArrowRight size={17}/></a></Magnetic><a className="text-btn" href="#metodo"><MousePointer2 size={15}/> Cómo funciona</a></div></div><div className="hero-visual"><div className="orbit orbit-a"/><div className="orbit orbit-b"/><TiltCard className="hero-card"><img src={items[0]?.image}/><div className="hero-card-overlay"/><div className="hero-card-label"><span>01 / SELECCIÓN</span><b>Favorito de Miwuko</b><small>Elegido por comodidad, calidad y uso diario.</small></div><div className="hero-card-index">M<span>W</span></div></TiltCard><motion.div className="floating-stat" initial={{opacity:0,x:30}} animate={{opacity:1,x:0}} transition={{delay:.8}}><span>4.8</span><div><b>valoración media</b><small>de nuestra selección</small></div></motion.div></div><a className="scroll-cue" href="#productos"><span>SCROLL TO EXPLORE</span><ArrowDown size={14}/></a></section>

<section className="marquee"><div><span>MENOS RUIDO</span><i/> <span>MEJORES DECISIONES</span><i/> <span>GUÍAS REALES</span><i/> <span>COMPARA · FILTRA · ELIGE</span><i/></div><div aria-hidden="true"><span>MENOS RUIDO</span><i/> <span>MEJORES DECISIONES</span><i/> <span>GUÍAS REALES</span><i/> <span>COMPARA · FILTRA · ELIGE</span><i/></div></section>

<section id="metodo" className="method"><Reveal><span className="kicker">No es otra tienda</span><h2>Una capa de criterio<br/><em>antes de comprar.</em></h2></Reveal><div className="method-grid"><Reveal delay={.08}><div className="method-card large"><span className="method-num">01</span><div className="method-icon"><Search/></div><h3>Filtramos el ruido.</h3><p>No necesitas 200 resultados. Necesitas saber cuáles merece la pena mirar.</p><div className="scan-line"/></div></Reveal><Reveal delay={.16}><div className="method-card"><span className="method-num">02</span><div className="method-icon"><Scale/></div><h3>Comparamos lo importante.</h3><p>Precio, valoración, materiales y lo que realmente cambia la experiencia.</p></div></Reveal><Reveal delay={.24}><div className="method-card"><span className="method-num">03</span><div className="method-icon"><Heart/></div><h3>Pensamos en el día a día.</h3><p>Menos postureo. Más productos que solucionan pequeños problemas.</p></div></Reveal></div></section>

<section id="productos" className="section products-section"><div className="section-head"><Reveal><span className="kicker">01 — Selección Miwuko</span><h2>Productos que<br/><em>merece la pena mirar.</em></h2></Reveal><Reveal><p>Una selección pequeña y curada. Busca, filtra y añade hasta tres productos al comparador.</p></Reveal></div><div className="toolbar"><div className="chips">{cats.map(c=><button className={category===c?'active':''} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div><label className="search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar producto..."/></label></div><div className="product-grid">{visible.map((p,i)=><Reveal key={p.id} delay={i*.06}><TiltCard className="product"><div className="product-img"><img src={p.image}/><div className="product-shine"/><span>{p.tag}</span><button className={compare.some(x=>x.id===p.id)?'compare on':'compare'} onClick={()=>toggle(p)}><Scale size={14}/>{compare.some(x=>x.id===p.id)?'Añadido':'Comparar'}</button></div><div className="product-body"><div className="rating"><Star size={13} fill="currentColor"/> {p.rating}</div><h3>{p.name}</h3><p>{p.description}</p><div className="pros">{p.pros.slice(0,2).map(x=><span key={x}>{x}</span>)}</div><div className="product-foot"><strong>{p.price}</strong><a href={p.affiliateUrl} target="_blank">Ver oferta <ExternalLink size={13}/></a></div></div></TiltCard></Reveal>)}</div></section>

<section className="feature-showcase"><div className="feature-copy"><span className="kicker">02 — Pensado para decidir</span><h2>Cuando un producto<br/><em>resuelve algo.</em></h2><p>La mejor recomendación no es la que tiene más estrellas. Es la que encaja con el problema que quieres resolver.</p><Magnetic><a className="btn light" href="#guias">Explorar guías <ArrowRight size={16}/></a></Magnetic></div><div className="feature-stack"><TiltCard className="feature-image main"><img src={items[2]?.image}/><div><span>DESCANSO</span><b>¿Tu perro duerme realmente cómodo?</b></div></TiltCard><TiltCard className="mini-card"><Zap size={18}/><b>Problema → solución</b><span>Descubre qué características importan.</span></TiltCard><TiltCard className="mini-card second"><ShieldCheck size={18}/><b>Menos marketing</b><span>Más criterios para comparar.</span></TiltCard></div></section>

<section id="comparador" className="compare-section"><div className="section-head"><Reveal><span className="kicker">03 — Herramienta</span><h2>Compara antes<br/><em>de decidir.</em></h2></Reveal><Reveal><p>Añade hasta tres productos y mira sus diferencias de un vistazo.</p></Reveal></div>{compare.length===0?<div className="empty"><div className="empty-ring"><Scale size={24}/></div><b>Aún no has añadido productos.</b><span>Pulsa «Comparar» en cualquiera de las tarjetas.</span><a href="#productos">Elegir productos <ArrowRight size={14}/></a></div>:<div className="compare-table"><div className="compare-row labels"><span>PRODUCTO</span>{compare.map(p=><b key={p.id}>{p.name}</b>)}</div><div className="compare-row"><span>PRECIO</span>{compare.map(p=><b key={p.id}>{p.price}</b>)}</div><div className="compare-row"><span>VALORACIÓN</span>{compare.map(p=><span key={p.id}>★ {p.rating}/5</span>)}</div><div className="compare-row"><span>DESTACA POR</span>{compare.map(p=><span key={p.id}>{p.pros[0]}</span>)}</div><div className="compare-row"><span>ENLACE</span>{compare.map(p=><a key={p.id} href={p.affiliateUrl}>Ver producto <ArrowRight size={14}/></a>)}</div></div>}</section>

<section id="guias" className="section guides"><div className="section-head"><Reveal><span className="kicker">04 — Publicaciones</span><h2>Antes de comprar,<br/><em>entiende qué necesitas.</em></h2></Reveal><a className="text-btn" href="#">Ver todas <ArrowRight size={16}/></a></div><div className="posts">{posts.map((p,i)=><Reveal key={p.title} delay={i*.1}><motion.a href="#" className="post" whileHover={{y:-9}}><img src={p.image}/><div className="post-shade"/><div className="post-content"><span>{p.category} · {p.time}</span><h3>{p.title}</h3><b>Leer guía <ArrowRight size={15}/></b></div><div className="post-number">0{i+1}</div></motion.a></Reveal>)}</div></section>

<section className="bento"><Reveal><div className="bento-intro"><span className="kicker">Miwuko / manifesto</span><h2>Menos pestañas.<br/><em>Más confianza.</em></h2><p>Estamos construyendo una biblioteca de decisiones útiles para quienes conviven con mascotas y no quieren comprar a ciegas.</p></div></Reveal><Reveal delay={.1}><div className="bento-card quote"><span>“</span><p>Lo importante no es encontrar <em>más</em> productos. Es encontrar el que tiene sentido para ti.</p><small>— MIWUKO</small></div></Reveal><Reveal delay={.2}><div className="bento-card stat"><span>SELECCIÓN</span><strong>24<span>+</span></strong><small>productos que iremos incorporando</small></div></Reveal><Reveal delay={.3}><div className="bento-card dark"><Sparkles/><b>Una forma más tranquila de comprar.</b><span>Sin listas interminables.</span></div></Reveal></section>

<section className="final-cta"><div className="cta-grid"/><span className="kicker">05 — Empieza por aquí</span><h2>Encuentra algo<br/><em>que les haga bien.</em></h2><Magnetic><a className="btn primary big" href="#productos">Ver selección <ArrowRight size={17}/></a></Magnetic></section></main>

<footer><div className="logo"><span className="logo-mark">M</span>miwuko</div><span>Recomendaciones para vivir mejor con ellos.</span><span>© 2026 Miwuko</span><a href="#">Instagram ↗</a></footer>
<AnimatePresence>{compare.length>0&&<motion.div className="compare-pill" initial={{y:100,opacity:0}} animate={{y:0,opacity:1}} exit={{y:100,opacity:0}}><Scale size={16}/><b>{compare.length}</b><span>seleccionados</span><a href="#comparador">Ver comparador</a><button onClick={()=>setCompare([])}><X size={15}/></button></motion.div>}</AnimatePresence></div>}
