import{useEffect,useMemo,useState}from'react';import{AnimatePresence,motion,useMotionValue,useSpring}from'framer-motion';import{ArrowDown,ArrowRight,ExternalLink,Menu,Search,Scale,Star,X,Sparkles,MousePointer2,ShieldCheck,Zap,Heart}from'lucide-react';import{products as fallback,posts,Product}from'./data';import FolderFloat from './components/FolderFloat';import TechText from './components/TechText';

const SHEET_URL=import.meta.env.VITE_SHEET_CSV_URL as string|undefined;
async function loadProducts():Promise<Product[]>{if(!SHEET_URL)return fallback;try{const r=await fetch(SHEET_URL);const csv=await r.text();const rows=csv.trim().split(/\r?\n/).map(x=>x.split(',').map(v=>v.replace(/^"|"$/g,'')));const h=rows.shift()||[];return rows.map((row,i)=>{const o=Object.fromEntries(h.map((k,j)=>[k,row[j]||'']));return{id:o.id||'sheet-'+i,name:o.name,category:o.category||'Otros',price:o.price||'',rating:Number(o.rating)||4.5,tag:o.tag||'Recomendado',image:o.image,description:o.description,pros:(o.pros||'').split('|').filter(Boolean),affiliateUrl:o.affiliateUrl||'#'}})}catch{return fallback}}

function ScrollProgress(){const[p,setP]=useState(0);useEffect(()=>{const f=()=>{const h=document.documentElement;setP(h.scrollHeight>h.clientHeight?window.scrollY/(h.scrollHeight-h.clientHeight)*100:0)};window.addEventListener('scroll',f,{passive:true});f();return()=>window.removeEventListener('scroll',f)},[]);return <div className="scroll-progress" style={{transform:'scaleX('+p/100+')'}}/>}
function Reveal({children,className='',delay=0}:{children:React.ReactNode;className?:string;delay?:number}){return <motion.div className={className} initial={{opacity:0,y:30,filter:'blur(8px)'}} whileInView={{opacity:1,y:0,filter:'blur(0px)'}} viewport={{once:true,margin:'-70px'}} transition={{duration:.72,delay,ease:[.22,1,.36,1]}}>{children}</motion.div>}
function Magnetic({children,className='' }:{children:React.ReactNode;className?:string}){const x=useMotionValue(0),y=useMotionValue(0),sx=useSpring(x,{stiffness:180,damping:14}),sy=useSpring(y,{stiffness:180,damping:14});return <motion.div className={className} style={{x:sx,y:sy}} onMouseMove={e=>{const r=e.currentTarget.getBoundingClientRect();x.set((e.clientX-r.left-r.width/2)*.15);y.set((e.clientY-r.top-r.height/2)*.15)}} onMouseLeave={()=>{x.set(0);y.set(0)}}>{children}</motion.div>}
function TiltCard({children,className='' }:{children:React.ReactNode;className?:string}){const rx=useMotionValue(0),ry=useMotionValue(0),sx=useSpring(rx,{stiffness:180,damping:20}),sy=useSpring(ry,{stiffness:180,damping:20});return <motion.div className={className} style={{rotateX:sx,rotateY:sy,transformPerspective:900}} onMouseMove={e=>{const r=e.currentTarget.getBoundingClientRect();rx.set(-((e.clientY-r.top)/r.height-.5)*6);ry.set(((e.clientX-r.left)/r.width-.5)*6)}} onMouseLeave={()=>{rx.set(0);ry.set(0)}}>{children}</motion.div>}

const categoryInfo=[
 {name:'Todos',sub:'Todo lo que necesitas',value:'Todos'},
 {name:'Paseo',sub:'Salir y explorar',value:'Paseo'},
 {name:'Hidratación',sub:'Beber mejor',value:'Hidratación'},
 {name:'Alimentación',sub:'Comer mejor',value:'Alimentación'},
 {name:'Descanso',sub:'Dormir a gusto',value:'Descanso'},
 {name:'Higiene',sub:'Cuidado diario',value:'Higiene'},
 {name:'Juguetes',sub:'Juego y estimulación',value:'Juguetes'}
];
function CategoryButtons({active,onSelect}:{active:string;onSelect:(x:string)=>void}){return <FolderFloat items={categoryInfo} label="Explorar categorías" sublabel="7 formas de encontrar lo que necesitas" trigger="click" closeOnSelect physics active={active} onSelect={onSelect}/>}
function TechHeroText(){return <TechText text="MIWUKO" fontWeight={700} fontSize={150} reveal="letter" dashLength={5} dashGap={3} specks={18} accentColor="#71805d"/>}
function GuideFolder({onOpen}:{onOpen:(p:(typeof posts)[number])=>void}){
 const guideItems=posts.map(p=>({name:p.title,sub:p.category+' · '+p.time,value:p.title}));
 return <FolderFloat items={guideItems} label="Biblioteca de guías" sublabel={posts.length+' guías para decidir mejor'} trigger="click" closeOnSelect physics onSelect={value=>{const p=posts.find(x=>x.title===value);if(p)onOpen(p)}}/>;
}

export default function App(){const[items,setItems]=useState<Product[]>(fallback),[category,setCategory]=useState('Todos'),[compare,setCompare]=useState<Product[]>([]),[search,setSearch]=useState(''),[menu,setMenu]=useState(false),[mouse,setMouse]=useState({x:0,y:0}),[guide,setGuide]=useState<(typeof posts)[number]|null>(null);useEffect(()=>{loadProducts().then(setItems);const f=(e:MouseEvent)=>setMouse({x:e.clientX, y:e.clientY});window.addEventListener('mousemove',f,{passive:true});return()=>window.removeEventListener('mousemove',f)},[]);const cats=['Todos',...Array.from(new Set(items.map(p=>p.category)))];const visible=useMemo(()=>items.filter(p=>(category==='Todos'||p.category===category)&&p.name.toLowerCase().includes(search.toLowerCase())),[items,category,search]);const toggle=(p:Product)=>setCompare(c=>c.some(x=>x.id===p.id)?c.filter(x=>x.id!==p.id):c.length<3?[...c,p]:c);

return <div className="app"><ScrollProgress/><div className="cursor-glow" style={{left:mouse.x,top:mouse.y}}/><div className="noise"/><header className="nav"><a className="logo" href="#"><span className="logo-mark">M</span>miwuko</a><nav className={menu?'open':''}><a href="#productos">Productos</a><a href="#metodo">Método</a><a href="#comparador">Comparador</a><a href="#guias">Guías</a></nav><Magnetic className="nav-cta"><a href="#productos">Explorar <ArrowRight size={14}/></a></Magnetic><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>

<main><section className="hero"><div className="hero-grid"/><div className="hero-copy"><motion.div className="eyebrow" initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.2}}><span className="eyebrow-dot"/> RECOMENDACIONES PARA GENTE QUE QUIERE ELEGIR BIEN</motion.div><TechHeroText/><motion.p initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.7}}>Productos, comparativas y guías prácticas para cuidar mejor de ellos <em>sin perder horas buscando.</em></motion.p><div className="hero-actions"><Magnetic><a className="btn primary" href="#productos">Descubrir selección <ArrowRight size={17}/></a></Magnetic><a className="text-btn" href="#metodo"><MousePointer2 size={15}/> Cómo funciona</a></div></div><div className="hero-visual"><div className="orbit orbit-a"/><div className="orbit orbit-b"/><TiltCard className="hero-card"><img src={items[0]?.image}/><div className="hero-card-overlay"/><div className="hero-card-label"><span>01 / SELECCIÓN</span><b>Favorito de Miwuko</b><small>Elegido por comodidad, calidad y uso diario.</small></div><div className="hero-card-index">M<span>W</span></div></TiltCard><motion.div className="floating-stat" initial={{opacity:0,x:30}} animate={{opacity:1,x:0}} transition={{delay:.9}}><span>4.8</span><div><b>valoración media</b><small>de nuestra selección</small></div></motion.div></div><a className="scroll-cue" href="#productos"><span>SCROLL TO EXPLORE</span><ArrowDown size={14}/></a></section>

<section className="category-section" id="categorias"><Reveal><span className="kicker">01 — Explora por necesidad</span><h2>¿Qué necesita<br/><em>hoy?</em></h2><p>Elige una categoría y te llevamos directamente a los productos relacionados.</p></Reveal><CategoryButtons active={category} onSelect={x=>{setCategory(x);document.getElementById('productos')?.scrollIntoView({behavior:'smooth'})}}/></section>

<section className="marquee"><div><span>PASEO</span><i/><span>HIDRATACIÓN</span><i/><span>ALIMENTACIÓN</span><i/><span>DESCANSO</span><i/><span>COMPARA · FILTRA · ELIGE</span><i/></div><div aria-hidden="true"><span>PASEO</span><i/><span>HIDRATACIÓN</span><i/><span>ALIMENTACIÓN</span><i/><span>DESCANSO</span><i/><span>COMPARA · FILTRA · ELIGE</span><i/></div></section>

<section id="metodo" className="method"><Reveal><span className="kicker">02 — Nuestro criterio</span><h2>Una capa de criterio<br/><em>antes de comprar.</em></h2></Reveal><div className="method-grid"><Reveal delay={.08}><div className="method-card large"><span className="method-num">01</span><div className="method-icon"><Search/></div><h3>Filtramos el ruido.</h3><p>No necesitas 200 resultados. Necesitas saber cuáles merece la pena mirar.</p><div className="scan-line"/></div></Reveal><Reveal delay={.16}><div className="method-card"><span className="method-num">02</span><div className="method-icon"><Scale/></div><h3>Comparamos lo importante.</h3><p>Precio, valoración, materiales y lo que realmente cambia la experiencia.</p></div></Reveal><Reveal delay={.24}><div className="method-card"><span className="method-num">03</span><div className="method-icon"><Heart/></div><h3>Pensamos en el día a día.</h3><p>Menos postureo. Más productos que solucionan pequeños problemas.</p></div></Reveal></div></section>

<section id="productos" className="section products-section"><div className="section-head"><Reveal><span className="kicker">03 — Selección Miwuko</span><h2>Productos que<br/><em>merece la pena mirar.</em></h2></Reveal><Reveal><p>Una selección pequeña y curada. Busca, filtra y añade hasta tres productos al comparador.</p></Reveal></div><div className="toolbar"><div className="chips">{cats.map(c=><button className={category===c?'active':''} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div><label className="search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar producto..."/></label></div><div className="product-grid">{visible.map((p,i)=><Reveal key={p.id} delay={i*.06}><TiltCard className="product"><div className="product-img"><img src={p.image}/><div className="product-shine"/><span>{p.tag}</span><button className={compare.some(x=>x.id===p.id)?'compare on':'compare'} onClick={()=>toggle(p)}><Scale size={14}/>{compare.some(x=>x.id===p.id)?'Añadido':'Comparar'}</button></div><div className="product-body"><div className="rating"><Star size={13} fill="currentColor"/> {p.rating}</div><h3>{p.name}</h3><p>{p.description}</p><div className="pros">{p.pros.slice(0,2).map(x=><span key={x}>{x}</span>)}</div><div className="product-foot"><strong>{p.price}</strong><a href={p.affiliateUrl} target="_blank">Ver oferta <ExternalLink size={13}/></a></div></div></TiltCard></Reveal>)}</div></section>

<section className="feature-showcase"><div className="feature-copy"><span className="kicker">04 — Pensado para decidir</span><h2>Cuando un producto<br/><em>resuelve algo.</em></h2><p>La mejor recomendación no es la que tiene más estrellas. Es la que encaja con el problema que quieres resolver.</p><Magnetic><a className="btn light" href="#guias">Explorar guías <ArrowRight size={16}/></a></Magnetic></div><div className="feature-stack"><TiltCard className="feature-image main"><img src={items[2]?.image}/><div><span>DESCANSO</span><b>¿Tu perro duerme realmente cómodo?</b></div></TiltCard><TiltCard className="mini-card"><Zap size={18}/><b>Problema → solución</b><span>Descubre qué características importan.</span></TiltCard><TiltCard className="mini-card second"><ShieldCheck size={18}/><b>Menos marketing</b><span>Más criterios para comparar.</span></TiltCard></div></section>

<section id="comparador" className="compare-section"><div className="section-head"><Reveal><span className="kicker">05 — Herramienta</span><h2>Compara antes<br/><em>de decidir.</em></h2></Reveal><Reveal><p>Añade hasta tres productos y mira sus diferencias de un vistazo.</p></Reveal></div>{compare.length===0?<div className="empty"><div className="empty-ring"><Scale size={24}/></div><b>Aún no has añadido productos.</b><span>Pulsa «Comparar» en cualquiera de las tarjetas.</span><a href="#productos">Elegir productos <ArrowRight size={14}/></a></div>:<div className="compare-table"><div className="compare-row labels"><span>PRODUCTO</span>{compare.map(p=><b key={p.id}>{p.name}</b>)}</div><div className="compare-row"><span>PRECIO</span>{compare.map(p=><b key={p.id}>{p.price}</b>)}</div><div className="compare-row"><span>VALORACIÓN</span>{compare.map(p=><span key={p.id}>★ {p.rating}/5</span>)}</div><div className="compare-row"><span>DESTACA POR</span>{compare.map(p=><span key={p.id}>{p.pros[0]}</span>)}</div><div className="compare-row"><span>ENLACE</span>{compare.map(p=><a key={p.id} href={p.affiliateUrl}>Ver producto <ArrowRight size={14}/></a>)}</div></div>}</section>

<section id="guias" className="section guides"><div className="section-head"><Reveal><span className="kicker">06 — Guías para decidir</span><h2>Antes de comprar,<br/><em>entiende qué necesitas.</em></h2></Reveal><span className="guide-hint">Explora la biblioteca y abre una guía <ArrowRight size={14}/></span></div><GuideFolder onOpen={setGuide}/></section>

<section className="bento"><Reveal><div className="bento-intro"><span className="kicker">Miwuko / manifesto</span><h2>Menos pestañas.<br/><em>Más confianza.</em></h2><p>Estamos construyendo una biblioteca de decisiones útiles para quienes conviven con mascotas y no quieren comprar a ciegas.</p></div></Reveal><Reveal delay={.1}><div className="bento-card quote"><span>“</span><p>Lo importante no es encontrar <em>más</em> productos. Es encontrar el que tiene sentido para ti.</p><small>— MIWUKO</small></div></Reveal><Reveal delay={.2}><div className="bento-card stat"><span>SELECCIÓN</span><strong>24<span>+</span></strong><small>productos que iremos incorporando</small></div></Reveal><Reveal delay={.3}><div className="bento-card dark"><Sparkles/><b>Una forma más tranquila de comprar.</b><span>Sin listas interminables.</span></div></Reveal></section>

<section className="final-cta"><div className="cta-grid"/><span className="kicker">07 — Empieza por aquí</span><h2>Encuentra algo<br/><em>que les haga bien.</em></h2><Magnetic><a className="btn primary big" href="#productos">Ver selección <ArrowRight size={17}/></a></Magnetic></section></main>

<footer><div className="logo"><span className="logo-mark">M</span>miwuko</div><span>Recomendaciones para vivir mejor con ellos.</span><span>© 2026 Miwuko</span><a href="#">Instagram ↗</a></footer>
<AnimatePresence>{compare.length>0&&<motion.div className="compare-pill" initial={{y:100,opacity:0}} animate={{y:0,opacity:1}} exit={{y:100,opacity:0}}><Scale size={16}/><b>{compare.length}</b><span>seleccionados</span><a href="#comparador">Ver comparador</a><button onClick={()=>setCompare([])}><X size={15}/></button></motion.div>}{guide&&<motion.div className="guide-modal-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setGuide(null)}><motion.div className="guide-modal" initial={{y:35,scale:.96}} animate={{y:0,scale:1}} exit={{y:35,scale:.96}} onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setGuide(null)}><X/></button><img src={guide.image}/><div><span>{guide.category} · {guide.time}</span><h3>{guide.title}</h3><p>Esta guía forma parte de la biblioteca de Miwuko. Aquí encontrarás los criterios que importan, qué debes mirar y qué errores conviene evitar antes de comprar.</p><button className="modal-action" onClick={()=>{setGuide(null);document.getElementById('productos')?.scrollIntoView({behavior:'smooth'})}}>Ver productos relacionados <ArrowRight size={15}/></button></div></motion.div></motion.div>}</AnimatePresence></div>}
