export type Product={id:string;name:string;category:string;price:string;rating:number;tag:string;image:string;description:string;pros:string[];affiliateUrl:string;species:'perro'|'gato'|'ambos'};
export const products:Product[]=[
{id:'p1',name:'Arnés AirFit Pro',category:'Paseo',price:'29,99 €',rating:4.8,tag:'Más recomendado',image:'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=900&q=85',description:'Ajuste cómodo y seguro para paseos diarios.',pros:['Ajuste regulable','Material transpirable','Fácil de poner'],affiliateUrl:'#',species:'perro'},
{id:'p2',name:'Fuente FreshFlow',category:'Hidratación',price:'34,90 €',rating:4.7,tag:'Para beber más',image:'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=900&q=85',description:'Fuente silenciosa pensada para estimular la hidratación.',pros:['Filtro incluido','Bajo ruido','Limpieza sencilla'],affiliateUrl:'#',species:'ambos'},
{id:'p3',name:'Cama CloudNest',category:'Descanso',price:'42,95 €',rating:4.9,tag:'Favorito',image:'https://images.unsplash.com/photo-1583511655826-05700d52f4d9?auto=format&fit=crop&w=900&q=85',description:'Cama mullida para convertir cualquier rincón en refugio.',pros:['Muy acolchada','Funda lavable','Base antideslizante'],affiliateUrl:'#',species:'ambos'},
{id:'p4',name:'Comedero SlowBowl',category:'Alimentación',price:'19,90 €',rating:4.6,tag:'Problema → solución',image:'https://images.unsplash.com/photo-1544568100-847a948585b9?auto=format&fit=crop&w=900&q=85',description:'Diseñado para hacer más pausada la hora de comer.',pros:['Antideslizante','Fácil de lavar','Diseño slow'],affiliateUrl:'#',species:'ambos'}
,
{id:'p5',name:'Kit CleanPaw',category:'Higiene',price:'24,90 €',rating:4.7,tag:'Cuidado diario',image:'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=900&q=85',description:'Accesorios sencillos para mantener limpio a tu perro después de cada salida.',pros:['Limpieza rápida','Fácil de guardar','Uso diario'],affiliateUrl:'#',species:'perro'},
{id:'p6',name:'Puzzle Treat Play',category:'Juguetes',price:'21,90 €',rating:4.8,tag:'Estimulación',image:'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?auto=format&fit=crop&w=900&q=85',description:'Juguete interactivo para convertir los premios en un pequeño reto mental.',pros:['Estimulación mental','Dificultad ajustable','Material resistente'],affiliateUrl:'#',species:'ambos'}];
export type GuideSection={heading:string;text:string;bullets?:string[]};
export type Guide={title:string;category:string;time:string;image:string;intro:string;sections:GuideSection[];takeaways:string[]};

export const posts:Guide[]=[
{title:'Cómo elegir el arnés perfecto para tu perro',category:'Guía de compra',time:'6 min',image:'https://images.unsplash.com/photo-1558929996-da64ba858215?auto=format&fit=crop&w=1000&q=85',intro:'Un buen arnés no debería complicar el paseo. Debería repartir la presión, permitir movimiento y quedar bien ajustado sin convertirse en una pelea cada vez que toca salir.',sections:[
{heading:'1. Empieza por el ajuste',text:'Mide el contorno del pecho siguiendo las indicaciones del fabricante. El arnés debe quedar firme, pero no apretado: como referencia práctica, deberías poder pasar dos dedos entre la cinta y el cuerpo.',bullets:['Comprueba el ajuste después de ponerlo.','Evita que las correas rocen detrás de las patas delanteras.','Revisa el ajuste si tu perro cambia de peso.']},
{heading:'2. Mira dónde reparte la fuerza',text:'Para paseos cotidianos interesa que la construcción distribuya la tensión por el pecho en lugar de concentrarla en una zona pequeña del cuello. También importa que el perro pueda caminar, girar y sentarse sin restricciones.',bullets:['Pecheras acolchadas cuando el contacto sea frecuente.','Correas regulables para adaptar el arnés.','Anilla y costuras bien terminadas.']},
{heading:'3. No compres solo por la estética',text:'Un diseño bonito no sustituye a un buen patrón. Prioriza comodidad, facilidad para ponerlo y materiales adecuados al uso que tendrá. Si tu perro tira mucho, consulta además con un profesional de educación canina para elegir el sistema apropiado.',bullets:['Piensa en el uso real: paseo corto, montaña o ciudad.','Comprueba cómo se limpia.','Valora cuánto tardas en colocarlo correctamente.']}
],takeaways:['Ajuste firme sin apretar','Libertad de movimiento','Materiales y costuras pensados para el uso diario']},
{title:'7 cosas que tu mascota necesita y quizá no tengas',category:'Checklist',time:'5 min',image:'https://images.unsplash.com/photo-1601758174114-e711c0cbaa69?auto=format&fit=crop&w=1000&q=85',intro:'No hace falta llenar la casa de accesorios. Esta lista sirve para detectar pequeños básicos que pueden hacer más sencillo el día a día.',sections:[
{heading:'Antes de comprar, revisa estos 7 básicos',text:'La idea no es comprar por comprar, sino comprobar si existe algún problema recurrente en casa que todavía no has resuelto.',bullets:['Un lugar cómodo y estable para descansar.','Recipiente de agua adecuado y fácil de limpiar.','Sistema de alimentación adaptado a sus hábitos.','Accesorios seguros para salir al exterior.','Materiales de higiene para las rutinas habituales.','Algún juguete o actividad de estimulación.','Un sistema sencillo para guardar sus accesorios.']},
{heading:'Compra según una necesidad real',text:'Si algo funciona y no existe un problema que resolver, no necesitas sustituirlo. Cuando sí existe una fricción —agua que se ensucia rápido, comida que desaparece demasiado deprisa o accesorios desperdigados— tiene sentido buscar una solución específica.',bullets:['Define primero el problema.','Compara dos o tres alternativas.','Mide si la solución realmente mejora la rutina.']}
],takeaways:['Primero necesidad, después producto','Menos accesorios, mejor elegidos','Revisa seguridad y facilidad de limpieza']},
{title:'¿Fuente de agua o cuenco? Lo que debes mirar',category:'Comparativa',time:'4 min',image:'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=1000&q=85',intro:'Ambas opciones pueden servir. La diferencia está en cómo encajan con los hábitos de tu mascota, la limpieza que estás dispuesto a mantener y el espacio disponible.',sections:[
{heading:'Cuándo puede tener sentido una fuente',text:'Una fuente mantiene el agua en circulación y algunos modelos incorporan filtros. Puede ser interesante si tu mascota muestra más interés por el agua en movimiento o si quieres una opción con depósito mayor.',bullets:['Comprueba el ruido de la bomba.','Mira cuánto cuesta y cómo se cambia el filtro.','Comprueba qué piezas pueden lavarse fácilmente.']},
{heading:'Cuándo un cuenco puede ser suficiente',text:'Un cuenco sencillo es fácil de rellenar, limpiar y colocar en distintos lugares. Si tu mascota bebe bien con él, no hay necesidad de complicarlo.',bullets:['Busca una base estable.','Prioriza materiales fáciles de limpiar.','Elige un tamaño acorde con el animal.']},
{heading:'La pregunta importante',text:'No es qué producto es más sofisticado, sino cuál facilita mantener agua limpia y disponible. Si una solución añade mantenimiento que no vas a realizar, deja de ser una buena solución para tu rutina.',bullets:['Facilidad de limpieza','Estabilidad','Capacidad adecuada']}
],takeaways:['Agua limpia y disponible','Mantenimiento asumible','El hábito de tu mascota importa más que la moda']}
];